# Generated by Django 4.2.4 on 2023-08-21 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0004_cart_fath_items_alter_cartmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_fath',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
