# Generated by Django 4.2.4 on 2023-08-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_fath_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_fath',
            old_name='user',
            new_name='user_cart',
        ),
    ]
