# Generated by Django 4.2.4 on 2023-08-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_user_cart_fath_user_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_fath',
            old_name='user_cart',
            new_name='user',
        ),
    ]
